### PR TITLE
Extra parser class to allow instance reuse, memory buffers reuse.

### PR DESCRIPTION
**Pull request by zubrabubra**

### CODE REVIEW

**Comment by rmuller** [comment]
Did you benchmark this code? And yes, what is the performance gain compared with the trunk code?
In my experience the gain is very small, if any and highly platform dependent.
Otherwise, it is a nice addition.

**Comment by zubrabubra** [comment]
In my case it was used in DeviceHive server to reduce memory usage, garbage collection time, and finally have more CPU left for the application itself. But i'm not working with DH for a quite a long time now, thus probably would be good to close PR, as it looks like author deprecated library.

**Comment by rmuller** [comment]
Okay, fair enough.

BTW, I do not think this lib is deprecated. It is updated quite recently.

**Comment by zubrabubra** [comment]
@rmuller i saw, however PR was not accepted, nor rejected.

**Comment by zubrabubra** [comment]
Closing as there is better PR with JMH https://github.com/yonik/noggit/pull/20

**Pull request closed without merging**
